### ISSUE TITLE
[ENH] Write an accessor for results

### ISSUE THREAD

**Issue by TinasheMTapera** [PennLINC/FixelDB#4]
We should have an accessor for results for the fixel array object

```
fa <- FixelArray("foo")
fixels(fa) # the current accessor for the fixels

results(fa) # potential accessor for results, could you implement this?
```

**Comment by zhao-cy** [comment]
Before doing this, I will add the reading of results in "FixelArray" - currently it's NULL which means that no matter there is results in .h5 file, we can only get results <- NULL when loading .h5 file...

**Comment by TinasheMTapera** [comment]
I think it's ok to have the accessor check for results and report if there are none

```
## pseudocode
results <- function(fixelarray){

    ifelse( is.null(fixelarray@results),
        print("No results yet"), # if results group not in h5 give a warning
        return(fixelarray@results) ) # else parse and return the results group

}
```

**Comment by zhao-cy** [comment]
Yes, that's a good idea to use results accessor to check if results exist or not. 
But I mean, when we load .h5 file to get a FixelArray ([here](https://github.com/PennLINC/FixelDB/blob/master/R/FixelArray.R#L46)), we need to assign the slot "results" as the group "results" in the .h5 file. Currently, slot "results" is always assigned as "NULL" (see [here](https://github.com/PennLINC/FixelDB/blob/master/R/FixelArray.R#L94)). I think I need to fix this issue, otherwise there always won't have "results" slot in a FixelArray to proceed... Does this make sense?

**Comment by TinasheMTapera** [comment]
Good point, yeah I think your strategy makes sense!
